app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

/**
 * Authentication
 *
 * Allow a user to log in and log out of the application
 */
Route::get('login',     ['uses' => 'SessionController@create',  'as' => 'session.create']);
Route::post('login',     ['uses' => 'SessionController@store',  'as' => 'session.store']);
Route::get('logout',     ['uses' => 'SessionController@destroy',  'as' => 'session.destroy']);

Route::group(array('before' => 'auth'), function() {
    Route::get('/', ['uses' => 'HomeController@index',  'as' => 'home.index']);
    
    Route::resource('pattern', 'PatternController');
    Route::resource('result', 'ResultController');
});

app/views/layouts/footer.blade.php
&copy;&nbsp;GACHA&nbsp;{{ date('Y') }}

app/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@yield('title')</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <style type="text/css">
        body {
            padding-top: 70px;
        }
    </style>
    <script src="/js/jquery.min.js"></script>

    <link href="/css/font-awesome.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/js/ie10-viewport-bug-workaround.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        @include('layouts.navbar')
    </div>
</div>

<div class="container">
    @yield('content')
    <hr>

    @include('layouts.footer')
</div> <!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/js/bootstrap.min.js"></script>
</body>
</html>

app/views/layouts/navbar.blade.php
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{ URL::route('home.index') }}">GACHA</a>
</div>
<div class="navbar-collapse collapse">
    @if (!empty($user))
    <ul class="nav navbar-nav">
        <li><a href="{{ URL::route('pattern.index') }}">Patterns</a></li>
        <li><a href="{{ URL::route('result.index') }}">Player Results</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ $user['username'] }}<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
                <li><a href="{{ URL::route('session.destroy') }}">Logout</a></li>
            </ul>
        </li>
    </ul>
    @endif
</div><!--/.navbar-collapse -->